### ISSUE TITLE
cannot get camera info from /color/image_info

### ISSUE THREAD

**Issue by santidadday** [zitongbai/UR5e_Vision_Assemble#2]
作者你好，我在启动该项目`ros2 launch bringup simulation.launch.py`时遇到了一个问题，无法获取到/color/image_info，该问题应该是出现在obj_seg中。
我查看了register_depth.launch.py文件中的相机相关topic是没有问题的，但是在rviz和rqt中订阅的/color/image_raw均无法显示，请问作者有遇到这种情况吗，是否能否分享一下您的启动流程以及日志信息。
万分感谢，祝好

**Comment by zitongbai** [comment]
应该是缺少依赖，需要安装
```bash
sudo apt install ros-humble-compressed-image-transport
sudo apt install ros-humble-compressed-depth-image-transport
```

**Comment by santidadday** [comment]
非常感谢您的回复，确实是在压缩图像时出现的问题。我的解决方法是修改代码使图片不进行压缩，您推荐的安装方法我还没有测试，后续我会尝试使用压缩图片的形式进行该项目。
最后，感谢您的指导。祝好

**Comment by zitongbai** [comment]
不客气不客气
